from node:14-alpine
WORKDIR /usr/src/app

COPY dist /usr/src/app
COPY package*.json /usr/src/app
COPY .env /usr/src/app
COPY ssl /usr/src/app

RUN npm install
EXPOSE 3200
CMD ["node" , "./dist/index.js"]
